<?php include '../../../header.html'; ?>
        <section style='margin-top: 80px; margin-bottom: 80px;' class='container'>
        <div class='row'>

            <!-- O word-wrap coloca quebra de linha no texto dentro da div -->

            <div class='col-12 offset-md-2 col-md-8' style='word-wrap: break-word'>
        <h1 style="font-family: &quot;Times New Roman&quot;; text-align: center;"><b>dedededededed</b></h1><h1 style="font-family: &quot;Times New Roman&quot;; text-align: center;"><b><br></b></h1><h3 style="font-family: &quot;Times New Roman&quot;; text-align: justify;">dedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddaaeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.</h3><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;"><br></p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: center;"><img src="https://img-a.udemycdn.com/course/240x135/950390_270f_3.jpg" style="width: 240px;"></p><h3 style="font-family: &quot;Times New Roman&quot;; text-align: justify;">dedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddaaeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.</h3><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;"><br></p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: center;"><iframe frameborder="0" src="http://www.youtube.com/embed/R4ffrXsXaQw" width="640" height="360" class="note-video-clip"></iframe></p><h3 style="font-family: &quot;Times New Roman&quot;; text-align: justify;">dedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddaaeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.</h3><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;"><br></p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;"><br></p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;">Obrigado por terem lido.</p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;">Autor: Wil</p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;">Descrição: text text tex text text text</p><p style="font-family: &quot;Times New Roman&quot;; font-size: medium; text-align: justify;">Data: 09/01/2020</p>
              </div>
            </div>
          </section>
        <?php include '../../../footer.html'; ?>